---
title: "Enjeux de conservation du massif du Volcan"
format:
  html:
    self-contained: true
editor: visual
---

```{r}
#| include: false
# Anne Piron
# Avril 2026
# Carte DI - Volcan

library(leaflet) # carte interactive
library(dplyr)
library(sf) # pour les shape


# import du jeu de donnees DI global
enjeu <-st_read("06_Prio_Volcan_2026_v3.shp")
# verification import
class(enjeu)
plot(enjeu)

# leaflet = WGS 84
# on transforme car on est en UTM40S
enjeu <- st_transform(enjeu, 4326)
#verification
st_crs(enjeu)


# échelle de couleurs
# test 1 : pal <- colorFactor(palette = "Set2", domain = enjeu$DI_6cat)

breaks <- c(  0, 6.7, 13.3, 19.9, 26.6, 33.2, 39.9, 46.5, 53.2, 59.8, 66.4, 73.1, 79.7, 86.4, 93, 99.7)

labels <- paste0( "[",  head(breaks, -1), " - ",  tail(breaks, -1), "]")

enjeu$classe <- cut(
  enjeu$enjeux_Z,
  breaks = breaks,
  labels = labels,
  include.lowest = TRUE,
  right = FALSE
)

pal <- colorFactor(palette = c(
  "[0 - 6.7]" = "#F7FCF5",
  "[6.7 - 13.3]" = "#EDF8E9",
  "[13.3 - 19.9]" = "#E2F4DD",
  "[19.9 - 26.6]" = "#D2EDCB",
  "[26.6 - 33.2]" = "#BFE6B9",
  "[33.2 - 39.9]" = "#ABDDA4",
  "[39.9 - 46.5]" = "#94D390",
  "[46.5 - 53.2]" = "#7BC77C",
  "[53.2 - 59.8]" = "#60BA6C",
  "[59.8 - 66.4]" = "#44AC5E",
  "[66.4 - 73.1]" = "#329B51",
  "[73.1 - 79.7]" = "#218A44",
  "[79.7 - 86.4]" = "#0D7835",
  "[86.4 - 93]" = "#006217",
  "[93 - 99.7]" = "#00441B"
), domain = enjeu$classe)


```

Enjeux zonation ou enjeu texte ?

```{r}
#| echo: false

# Carte avec un point par relevé dont la couleur correspond à l'enjeu (DI_6cat) 

leaflet(enjeu) %>%
  addProviderTiles(providers$OpenTopoMap) |> # fond satellite
  #addTiles() %>%
  addPolygons(
    fillColor = ~pal(classe),
    color = "black", 
    weight = 0.6,
    fillOpacity = 0.7,
    popup = ~paste0(
      "<strong>Catégorie :</strong> ", classe, "<br>")
  ) %>%
  addLegend(
    "bottomright",
    pal = pal,
    values = ~classe,
    title = "Enjeux de conservation - Gradient issu de Zonation",
    opacity = 1
  )
```
